source 'https://github.com/CocoaPods/Specs.git '
platform :ios, '9.0'
target 'LoginRadiusAuthenticator' do

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

pod 'MBProgressHUD'

pod 'DYQRCodeDecoder'

end



